// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMLDrHe2MiSC9UpyTZcGsej1_BqLLneo',
    appId: '1:124193868831:web:74f31c3b6736d3ba88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    authDomain: 'vetementia.firebaseapp.com',
    storageBucket: 'vetementia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjgF6OwxyfbkASirGMp05koeBJ246GAq4',
    appId: '1:124193868831:android:d9eab3530325a28388d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    storageBucket: 'vetementia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-HqnhA5gMS4hZN_Kj-pKLU27NLR1zTo',
    appId: '1:124193868831:ios:52261dd31dfe16fa88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    storageBucket: 'vetementia.firebasestorage.app',
    iosBundleId: 'com.amine.vetementIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-HqnhA5gMS4hZN_Kj-pKLU27NLR1zTo',
    appId: '1:124193868831:ios:52261dd31dfe16fa88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    storageBucket: 'vetementia.firebasestorage.app',
    iosBundleId: 'com.amine.vetementIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFMLDrHe2MiSC9UpyTZcGsej1_BqLLneo',
    appId: '1:124193868831:web:e75ca400086e1a7b88d92a',
    messagingSenderId: '124193868831',
    projectId: 'vetementia',
    authDomain: 'vetementia.firebaseapp.com',
    storageBucket: 'vetementia.firebasestorage.app',
  );
}
